title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          instructions_position: above
          listable: hidden
          read_only: false
          input_type: text
          antlers: false
      -
        handle: service_icon
        field:
          mode: list
          restrict: true
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Service Icon'
          type: assets
          icon: assets
          instructions: 'This is for icon on services'
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: small_description
        field:
          input_type: text
          antlers: false
          display: 'Small Description'
          type: text
          icon: text
          instructions: 'This is mini description on Service'
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
